services:
  user:
    build:
      context: ../user
    ports:
      - "8003:8003"  
    depends_on:
      - note
      - permission
      - redis
      - rabbitmq

  permission:
    build:
      context: ../permission
    ports:
      - "8002:8002"

  note:
    build:
      context: ../note
    ports:
      - "8001:8001"
